### ISSUE TITLE
Tracing missing value and input fields

### ISSUE THREAD

**Issue by qk-santi** [Fantom-foundation/go-opera#497] opened 2023-08-09 15:19 UTC
**Describe the bug**
Some transactions do not have the `input` and `value` fields properly filled with the value sent within the transaction when tracing using 

**To Reproduce**
```
curl --request POST --data '[{"id":1,"jsonrpc":"2.0","method":"trace_block","params":["0x3C9FD22"]}]' -H "Content-Type: application/json" https://rpcapi-tracing.fantom.network | jq

...
{
			"action": {
				"callType": "call",
				"from": "0x9833ef72b30066df3319d9afd6826e777ed56cd0",
				"to": "0x040993fbf458b95871cd2d73ee2e09f4af6d56bb",
				"value": "0x0",
				"gas": "0x570c",
				"input": "0x"
			},
			"blockHash": "0x0003475c0000067d9659deb6f2e9611bba98b87e3da1379690bf471019423d74",
			"blockNumber": 63569186,
			"error": "Reverted",
			"subtraces": 0,
			"traceAddress": [],
			"transactionHash": "0x0b66ebd50b00526983b8e6082c820cc5ad71ff7bc449d576afa809e43afb92eb",
			"transactionPosition": 1,
			"type": "call"
		},
...
```

**Expected behavior**
For the same [transaction](https://ftmscan.com/tx/0x0b66ebd50b00526983b8e6082c820cc5ad71ff7bc449d576afa809e43afb92eb) in ftmscan, the value should be 52.38 FTM and input should be `0xe56461ad000000000000000000000000000000000000000000000000000000000000a86a0000000000000000000000009833ef72b30066df3319d9afd6826e777ed56cd0`

**Additional context**

**Comment by hawkaa** [comment] 2023-08-10 06:24
Hi. I found another related issue on block 0x45AF62.

To reproduce:

```
curl --request POST --data '[{"id":1,"jsonrpc":"2.0","method":"trace_block","params":["0x45AF62"]}]' -H "Content-Type: application/json" https://rpcapi-tracing.fantom.network | jq

...
{
					{
			"action": {
				"callType": "call",
				"from": "0x0000000000000000000000000000000000000000",
				"to": "0xd100a01e00000000000000000000000000000000",
				"value": "0x0",
				"gas": "0x0",
				"input": "0x"
			},
			"blockHash": "0x000015cd0000282920440437dca24e48ee76b4e2a052c7eaab5b96342b71d016",
			"blockNumber": 4566882,
			"error": "not able to decode tx",
			"subtraces": 0,
			"traceAddress": [],
			"transactionHash": "0x50277223db519cf6e56024647a3f1c6aee1568d95640221386cfec8673a3439f",
			"transactionPosition": 0,
			"type": "call"
		},
		{
			"action": {
				"callType": "call",
				"from": "0x0000000000000000000000000000000000000000",
				"to": "0xd100a01e00000000000000000000000000000000",
				"value": "0x0",
				"gas": "0x0",
				"input": "0x"
			},
			"blockHash": "0x000015cd0000282920440437dca24e48ee76b4e2a052c7eaab5b96342b71d016",
			"blockNumber": 4566882,
			"error": "not able to decode tx",
			"subtraces": 0,
			"traceAddress": [],
			"transactionHash": "0xda3e38fe5334105dd280544be10643c4a9fcbe1e749719a9e9bacb64b1155968",
			"transactionPosition": 1,
			"type": "call"
		},
...
```

Both transactions are successful, despite there being an error message on the two. value, gas, and input is also missing.

**Comment by jenikd** [comment] 2023-08-10 06:41
> 0xda3e38fe5334105dd280544be10643c4a9fcbe1e749719a9e9bacb64b1155968

This is already fixed with https://github.com/Fantom-foundation/go-opera/pull/491 and will go to next RC

**Comment by abigail1010** [comment] 2023-09-25 10:18
> **Describir el error** Algunas transacciones no tienen los campos y correctamente rellenados con el valor enviado dentro de la transacción al rastrear usando`input``value`
> 
> **Para reproducir**
> 
> ```
> curl --request POST --data '[{"id":1,"jsonrpc":"2.0","method":"trace_block","params":["0x3C9FD22"]}]' -H "Content-Type: application/json" https://rpcapi-tracing.fantom.network | jq
> 
> ...
> {
> 			"action": {
> 				"callType": "call",
> 				"from": "0x9833ef72b30066df3319d9afd6826e777ed56cd0",
> 				"to": "0x040993fbf458b95871cd2d73ee2e09f4af6d56bb",
> 				"value": "0x0",
> 				"gas": "0x570c",
> 				"input": "0x"
> 			},
> 			"blockHash": "0x0003475c0000067d9659deb6f2e9611bba98b87e3da1379690bf471019423d74",
> 			"blockNumber": 63569186,
> 			"error": "Reverted",
> 			"subtraces": 0,
> 			"traceAddress": [],
> 			"transactionHash": "0x0b66ebd50b00526983b8e6082c820cc5ad71ff7bc449d576afa809e43afb92eb",
> 			"transactionPosition": 1,
> 			"type": "call"
> 		},
> ...
> ```
> 
> **Comportamiento** esperado Para la misma [transacción](https://ftmscan.com/tx/0x0b66ebd50b00526983b8e6082c820cc5ad71ff7bc449d576afa809e43afb92eb) en ftmscan, el valor debe ser 52.38 FTM y la entrada debe ser `0xe56461ad000000000000000000000000000000000000000000000000000000000000a86a0000000000000000000000009833ef72b30066df3319d9afd6826e777ed56cd0`
> 
> **Contexto adicional**

**Closed as completed** 2024-02-02 06:38 UTC

**Comment by webgit63** [comment] 2024-12-25 19:57
Hello 

I'm Wayne Brown.
I been trying to cash out my assets since July/24.
I was talking to support on BitBuy ., Keith, 
Who told me someone was 
Possibly cashing my addresses out.
Can you please help me.

I'm old school when it 
Comes to all of this.

Merry Christmas,

Wayne Brown 

And I do have 12 word phrases, but I don't know what to do in fear of being scammed again.

**Comment by alialobidm** [comment] 2025-03-26 14:24
[](url)

**Comment by alialobidm** [comment] 2025-03-26 14:26
[](url)
