### ISSUE TITLE
Segmentation violation error on MacOS

### ISSUE THREAD

**Issue by abiro** [Fantom-foundation/go-opera#166] opened 2021-09-19 15:01 UTC
**Describe the bug**
Running a read-only node on MacOS Big Sur results in segmentation violation error.

**To Reproduce**

1. Compile 10ca6692 (current HEAD in master).
2. Run `build/opera --nodiscover --genesis mainnet.g`

**Expected behavior**
Opera should start syncing.

**Actual behavior**
Opera crashes with segmentation violation error:

```
INFO [09-19|16:46:28.872] Maximum peer count                       total=50
INFO [09-19|16:46:29.841] Genesis is already written               hash=0x4a53c5445584b3bfc20dbfb2ec18ae20037c716f3ba2d9e1da768a9deca17cb4
WARN [09-19|16:46:29.841] Sanitizing invalid parameter MinPrice of gasprice oracle provided=0 updated=0
INFO [09-19|16:46:30.231] Loaded local transaction journal         transactions=0 dropped=0
INFO [09-19|16:46:30.232] Regenerated local transaction journal    transactions=0 accounts=0
INFO [09-19|16:46:30.232] Starting peer-to-peer node               instance=go-opera/v1.0.2-rc.5-10ca6692-1630082373/darwin-amd64/go1.17.1
INFO [09-19|16:46:30.232] Transaction pool price threshold updated price=15,000,000,000
INFO [09-19|16:46:30.378] New local node record                    seq=7 id=c45bf06507c806b6 ip=127.0.0.1 udp=5050 tcp=5050
INFO [09-19|16:46:30.378] Started P2P networking                   self=enode://99e23f783bb135cd9f31332dbce9d9a8f5586df0305fc4a98dc1bf6d3b6e60fbbeca9571fd0b2f301e4d366ccb98615bcfb9fe949a9c7e20ae4a185f6313d482@127.0.0.1:5050
INFO [09-19|16:46:30.379] IPC endpoint opened                      url=/Users/abiro/Library/Lachesis/opera.ipc
WARN [09-19|16:46:30.380] Loaded snapshot journal                  diskroot=c48257..332820 diffs=missing
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff2033ac9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2033ac9e
stack: frame={sp:0x70000f22ce58, fp:0x70000f22cea8} stack=[0x70000f1ad338,0x70000f22cf38)
```

Full logs: https://pastebin.com/WBaLnMaM

**Software version:**
- MacOS Big Sur 11.6 (20G165) Intel
- go1.17.1 darwin/amd64

**Comment by uprendis** [comment] 2021-09-19 15:38
Hello @abiro,
Good day to you!
It seems that the issue is related to a calculation of available disk space for the datadir
Please try to use the `--datadir.minfreedisk=0` flag until the issue is fixed in a future release

**Comment by abiro** [comment] 2021-09-19 16:22
@uprendis thanks for the quick reply! It doesn't crash with the flag, but doesn't start to sync either. This is the command that I'm running:

`build/opera --nodiscover --genesis mainnet.g --datadir.minfreedisk=0`

Am I doing something wrong?

**Comment by uprendis** [comment] 2021-09-19 17:30
Why would you want to use the `--nodiscover` flag? It won't find peers automatically without discovery, hence you won't sync. You may want to either erase this flag or add peers statically with a config or using console

**Comment by abiro** [comment] 2021-09-19 21:54
Ah thanks @uprendis, thought that'd prevent broadcasting my IP address.

**Closed** 2021-11-03 09:55 UTC
